### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by crazysparrow69**
Improved Checkbox interface
Changed tests for new Checkbox

### CODE REVIEW

**Review by Dimdim28 — APPROVED** [review]
With this simplified logic checkbox component will be more reusable, thanks.

**Comment by crazysparrow69** [comment]
Appreciate it, bro

**Comment by crazysparrow69** [comment]
I want to express my sincere gratitude for your heartfelt appreciation. Your kind words mean a lot to me and truly brightened my day.

**Review by LikerFeed — COMMENTED** [review]
good!

**Pull request merged**
